apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sshd-data-pv-claim
spec:
  # https://docs.coreweave.com/coreweave-kubernetes/storage
  storageClassName: block-nvme-ord1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
